version: '2'

services:
  superset:
    image: thunderyy/superset-init
    command: superset runserver -p 8088
  nginx:
    build: nginx
    ports: 
      - "80:80"  

networks:
  default:
    external:
      name: main


